name: Use mlops-plugin (example)
on:
  push:
  pull_request:

jobs:
  mlops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Call the plugin from a different repo:
      # - Replace "cyndi-s/mlops-plugin@v1" with your tag/commit.
      - name: Run mlops-plugin
        uses: cyndi-s/mlops-plugin@v1
        with:
          mlflow_tracking_uri: ${{ secrets.MLFLOW_TRACKING_URI }}
          mlflow_token:        ${{ secrets.MLFLOW_TOKEN }}
          gist_id:             ${{ vars.GIST_ID }}
          gist_filename:       commitHistory.csv
          gist_token:          ${{ secrets.GIST_TOKEN }}
          trained_this_run:    "false"
